---
- name: Copy RPM Duplicati file to server
  get_url:
     url: 'https://updates.duplicati.com/beta/duplicati-2.0.5.1-2.0.5.1_beta_20200118.noarch.rpm'
     dest: /tmp/package.rpm

- name: Install Duplicati
  yum:
    name: /tmp/package.rpm
    state: latest

